# Generated by Django 6.0.2 on 2026-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_persona',
            field=models.CharField(choices=[('ZEN', 'Zen Guide (Mindfulness & Breath)'), ('STRATEGIST', 'Practical Strategist (Action & Goals)'), ('LISTENER', 'Empathetic Listener (Validation & Kindness)'), ('CATALYST', 'Growth Catalyst (Patterns & Reframing)')], default='ZEN', max_length=20),
        ),
    ]
